name: MLflow CI/CD Advance

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "🚀 Starting MLflow CI/CD..."

    - name: Checkout repo
      uses: actions/checkout@v3

   
    - name: Set up Miniconda with Python 3.12.7
      uses: conda-incubator/setup-miniconda@v3 
      with:
        name: MLflow CI/CD Advance

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "🚀 Starting MLflow CI/CD..."

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Miniconda with Python 3.12.7 and initialize shell
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12.7"
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: false 
        activate-environment: false 

    - name: Initialize Conda for current shell
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        # Atau jika menggunakan bash: source /home/runner/miniconda/bin/activate
        # Anda mungkin perlu menyesuaikan path '/usr/share/miniconda/'
        # Berdasarkan output log Anda: /usr/share/miniconda/lib/python3.13/site-packages/conda
        # Jadi path ke activate script kemungkinan di /usr/share/miniconda/bin/activate
        # ATAU gunakan "conda init" di run pertama, lalu cek outputnya untuk path yang benar.
        # Untuk kepastian, bisa coba:
        # CONDA_BASE=$(conda info --base)
        # source "$CONDA_BASE/etc/profile.d/conda.sh"
        # echo "Conda activated base environment."

    - name: Check Env (Python and Conda)
      run: |
        python --version
        conda --version
        # Sekarang 'activate' seharusnya ditemukan
        type activate && echo "Activate command found!" || echo "Activate command NOT found!"

    - name: Install dependencies
      run: pip install mlflow pandas scikit-learn xgboost

    - name: Set MLflow Tracking URI to Local
      run: export MLFLOW_TRACKING_URI=./mlruns

    - name: Run MLflow project
      run: mlflow run MLProjects -P data_folder=ecommerce_shipping_data_preprocessed

    - name: Install Docker dependency
      run: pip install docker

    - name: Upload MLflow artifacts (local mlruns folder)
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-model-artifact
        path: mlruns/

    - name: Build Docker Model
      run: |
        latest_run=$(ls -t mlruns/0 | head -n 1)
        mlflow models build-docker -m mlruns/0/$latest_run/artifacts/model -n shipping-delay

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker Image
      run: docker tag shipping-delay:latest ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest

    - name: Post Log in to Docker Hub
      run: echo "🧼 Logged out from Docker Hub"
      if: always()

    - name: Post set up Miniconda
      run: echo "🧹 Miniconda teardown complete"
      if: always()

    - name: Post Run actions/checkout@v3
      run: echo "🧽 Repo checkout done"
      if: always()

    - name: Complete job
      run: echo "✅ CI/CD workflow complete!"python-version: "3.12.7"
        miniconda-version: "latest" 
        activate-environment: false 
        auto-update-conda: true
        auto-activate-base: false 

    - name: Check Env (Python and Conda)
      run: |
        python --version
        conda --version
        # Cek apakah 'activate' tersedia
        type activate || echo "Activate command not found or not in PATH"

    - name: Install dependencies
      run: |
        # Instal MLflow CLI secara global agar 'mlflow run' bisa dieksekusi
        pip install mlflow
        # Dependensi proyek (pandas, scikit-learn) akan diurus oleh conda.yaml via mlflow run
        # dagshub tidak perlu diinstal jika tidak terintegrasi dengan DagsHub

    - name: Set MLflow Tracking URI to Local
      run: export MLFLOW_TRACKING_URI=./mlruns

    - name: Run MLflow project
      run: |
        mlflow run MLProjects -P data_folder=ecommerce_shipping_data_preprocessed

    - name: Install Docker dependency
      run: pip install docker

    - name: Upload MLflow artifacts (local mlruns folder)
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-model-artifact
        path: mlruns/ 

    - name: Build Docker Model
      run: |
        latest_run=$(ls -t mlruns/0 | head -n 1)
        mlflow models build-docker -m mlruns/0/$latest_run/artifacts/model -n shipping-delay

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker Image
      run: docker tag shipping-delay:latest ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest

    - name: Post Log in to Docker Hub
      run: echo "🧼 Logged out from Docker Hub"
      if: always()

    - name: Post set up Miniconda
      run: echo "🧹 Miniconda teardown complete"
      if: always()

    - name: Post Run actions/checkout@v3
      run: echo "🧽 Repo checkout done"
      if: always()

    - name: Complete job
      run: echo "✅ CI/CD workflow complete!"