name: MLflow CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        python-version: "3.12"
        auto-update-conda: true
        auto-activate-base: false

    - name: Initialize Conda
      run: |
        conda init bash
        source ~/.bashrc

    - name: Create Conda environment
      run: |
        conda env remove -n mlflow-env || true
        conda env create -f MLProjects/conda.yaml
        conda activate mlflow-env
        python -c "import mlflow; print(f'MLflow version: {mlflow.__version__}')"

    - name: Run MLflow project
      run: |
        conda activate mlflow-env
        export MLFLOW_TRACKING_URI=file://$GITHUB_WORKSPACE/mlruns
        export MLFLOW_EXPERIMENT_NAME="Shipping-Delay-Prediction"
        mlflow run MLProjects -P data_folder=ecommerce_shipping_data_preprocessed

    - name: Build Docker image
      run: |
        conda activate mlflow-env
        latest_run=$(ls -t mlruns/0 | head -n 1)
        mlflow models build-docker -m "mlruns/0/$latest_run/artifacts/model" -n "shipping-delay"

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag shipping-delay:latest ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest
        docker logout

    - name: Upload artifacts