name: MLflow CI/CD Advance

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        python-version: "3.12"
        auto-update-conda: true
        auto-activate-base: false

    - name: Initialize Conda
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc

    - name: Create Conda environment
      shell: bash -l {0}
      run: |
        # Hapus environment jika sudah ada
        conda env remove -n mlflow-env || true
        
        # Buat environment baru
        conda env create -f $GITHUB_WORKSPACE/MLProjects/conda.yaml
        
        # Aktifkan dan verifikasi
        conda activate mlflow-env
        conda list
        python -c "import mlflow; print(f'MLflow version: {mlflow.__version__}')"

    - name: Run MLflow project
      shell: bash -l {0}
      run: |
        conda activate mlflow-env
        export MLFLOW_TRACKING_URI=./mlruns
        mlflow run MLProjects -P data_folder=ecommerce_shipping_data_preprocessed --verbose

    - name: Build Docker image
      shell: bash -l {0}
      run: |
        conda activate mlflow-env
        latest_run=$(ls -t mlruns/0 | head -n 1)
        mlflow models build-docker -m "mlruns/0/$latest_run/artifacts/model" -n "shipping-delay"

    - name: Push to Docker Hub
      shell: bash -l {0}
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag shipping-delay:latest ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest
        docker logout

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns/