name: MLflow CI/CD Advance

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "🚀 Starting MLflow CI/CD..."

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12.7"
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: false

    - name: Proper Conda Initialization
      shell: bash -l {0}  # Critical: Use login shell
      run: |
        conda init bash
        source ~/.bashrc

    - name: Create and activate environment
      shell: bash -l {0}  # Critical: Use login shell
      run: |
        conda env create -f MLProjects/conda.yaml
        conda activate mlflow-env
        conda list

    - name: Verify environment
      shell: bash -l {0}
      run: |
        conda info
        which python
        python -c "import mlflow; print(mlflow.__version__)"

    - name: Debug Conda
      shell: bash -l {0}
      run: |
        echo "CONDA_PREFIX: $CONDA_PREFIX"
        echo "PATH: $PATH"
        conda env list

    - name: Run MLflow project
      shell: bash -l {0}
      run: |
        conda activate mlflow-env
        mlflow run MLProjects -P data_folder=ecommerce_shipping_data_preprocessed

    - name: Build Docker Model
      shell: bash -l {0}
      run: |
        conda activate mlflow-env
        latest_run=$(ls -t mlruns/0 | head -n 1)
        mlflow models build-docker -m "mlruns/0/$latest_run/artifacts/model" -n "shipping-delay"

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag and Push Docker Image
      run: |
        docker tag shipping-delay:latest ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest

    - name: Cleanup
      run: docker logout
      if: always()

    - name: Complete job
      run: echo "✅ CI/CD workflow complete!"