name: MLflow CI/CD Advance

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        python-version: "3.12" 
        auto-update-conda: true
        auto-activate-base: false

    - name: Initialize Conda
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc

    - name: Create environment from conda.yaml
      shell: bash -l {0}
      run: |
        conda env create -f MLProjects/conda.yaml --force
        conda activate mlflow-env
        conda list

    - name: Verify environment
      shell: bash -l {0}
      run: |
        conda activate mlflow-env
        python -c "import mlflow, xgboost; print(f'MLflow:{mlflow.__version__}, XGBoost:{xgboost.__version__}')"
        which python

    - name: Run MLflow project
      shell: bash -l {0}
      run: |
        conda activate mlflow-env
        export MLFLOW_TRACKING_URI=./mlruns
        mlflow run MLProjects -P data_folder=ecommerce_shipping_data_preprocessed --verbose

    - name: Prepare Docker artifacts
      shell: bash -l {0}
      run: |
        conda activate mlflow-env
        latest_run=$(ls -t mlruns/0 | head -n 1)
        echo "Latest run ID: $latest_run"
        ls -la "mlruns/0/$latest_run/artifacts/model"

    - name: Build and push Docker image
      shell: bash -l {0}
      run: |
        conda activate mlflow-env
        latest_run=$(ls -t mlruns/0 | head -n 1)
        mlflow models build-docker -m "mlruns/0/$latest_run/artifacts/model" -n "shipping-delay"
        
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag shipping-delay:latest ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest
        docker logout

    - name: Upload MLflow artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns/