name: MLflow CI/CD Advance

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "🚀 Starting MLflow CI/CD..."

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    - name: Check Env
      run: python --version

    - name: Install dependencies
      run: |
        pip install mlflow pandas scikit-learn

    - name: Set MLflow Tracking URI
      run: echo "MLFLOW_TRACKING_URI=http://127.0.0.1:5001" >> $GITHUB_ENV

    - name: Run MLflow project
      run: |
        export MLFLOW_TRACKING_URI=local
        mlflow run MLProjects -P data_folder=ecommerce_shipping_data_preprocessed


    - name: Install Python dependencies (for Docker)
      run: pip install docker mlflow

    - name: Upload to GitHub (simulasi Google Drive)
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-model-artifact
        path: mlruns/

    - name: Build Docker Model
      run: |
        latest_run=$(ls -t mlruns/0 | head -n 1)
        mlflow models build-docker -m mlruns/0/$latest_run/artifacts/model -n shipping-delay

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker Image
      run: docker tag shipping-delay:latest ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest

    - name: Post Log in to Docker Hub
      run: echo "🧼 Logged out from Docker Hub"
      if: always()

    - name: Post set up Python 3.12.7
      run: echo "🧹 Python teardown complete"
      if: always()

    - name: Post Run actions/checkout@v3
      run: echo "🧽 Repo checkout done"
      if: always()

    - name: Complete job
      run: echo "✅ CI/CD workflow complete!"
