name: MLflow CI/CD Advance

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "🚀 Starting MLflow CI/CD..."

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12.7"
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: false

    - name: Initialize Conda
      run: |
        source $CONDA/bin/activate
        conda init bash
        source ~/.bashrc

    - name: Check Environment
      run: |
        python --version
        conda --version
        conda info

    - name: Create Conda environment
      run: |
        conda env create -f MLProjects/conda.yaml
        conda activate mlflow-env
        conda list

    - name: Install additional dependencies
      run: |
        conda activate mlflow-env
        pip install docker

    - name: Set MLflow Tracking URI
      run: |
        export MLFLOW_TRACKING_URI=./mlruns
        echo "MLFLOW_TRACKING_URI set to $MLFLOW_TRACKING_URI"

    - name: Run MLflow project
      run: |
        conda activate mlflow-env
        mlflow run MLProjects -P data_folder=ecommerce_shipping_data_preprocessed

    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-model-artifact
        path: mlruns/

    - name: Build Docker Model
      run: |
        latest_run=$(ls -t mlruns/0 | head -n 1)
        mlflow models build-docker -m "mlruns/0/$latest_run/artifacts/model" -n "shipping-delay"

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag and Push Docker Image
      run: |
        docker tag shipping-delay:latest ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/shipping-delay:latest

    - name: Cleanup
      run: |
        echo "🧹 Cleaning up..."
        docker logout
      if: always()

    - name: Complete job
      run: echo "✅ CI/CD workflow complete!"